version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: postgres
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata